mysite/headshot/urls.py
from django.urls import path
from . import views

app_name = "shot"

urlpatterns = [
    path('', views.index, name='index'),
    path('loginsignup', views.loginsignup, name="loginsignup"),
    path('log_out', views.log_out, name="log_out"),
    path('logon', views.logon, name='logon'),
    path('signup', views.signup, name='signup'),
    path('hashtag/<str:hashtag_text>', views.hashtag, name='hashtag'),
    path('mention/<str:mention_text>', views.mention, name='mention'),
    path('post_shot', views.post_shot, name='post_shot'),
    path('author/<int:author_id>', views.author, name='author'),
    path('like/<int:shot_id>', views.like, name='like'),
    path('unlike/<int:shot_id>', views.unlike, name='unlike'),
    path('search', views.search, name='search'),
    path('follow/<int:author_id>', views.follow, name='follow'),
    path('unfollow/<int:author_id>', views.unfollow, name='unfollow'), 
    path('delete/<int:shot_id>', views.delete, name='delete'),
    path('comment/<int:shot_id>', views.post_comment, name='post_comment'),
    path('delete_comment/<int:comment_id>', views.delete_comment, name='delete_comment'),
    path('like_comment/<int:comment_id>', views.like_comment, name='like_comment'),
    path('unlike_comment/<int:comment_id>', views.unlike_comment, name='unlike_comment'),
    path('popular', views.popular, name='popular'),
    path('post', views.post, name='post'),
    path('test', views.test, name='test')
]  

mysite/mysite/urls.py
from django.contrib import admin 
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('shot/', include('headshot.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/headshot/models.py
from pyexpat import model
from django.db import models
from django.contrib.auth.models import User 

#models:
# - shot: pic, bio, user, time, likers (m2m user)
# - hashtags: hash_text, shots (m2m shot)
# - user: pfp, bio
# - mention: show to user or not, time


class Shot(models.Model):    
    shot_pic = models.ImageField(upload_to='images')
    shot_text = models.CharField(max_length=255)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author')
    time_pub = models.DateTimeField('date published', auto_now_add=True)
    likers = models.ManyToManyField(User, related_name='likers')
    mentions = models.ManyToManyField(User, through='Mention')

    def __str__(self):
        return f'{self.id} - {self.shot_text} - {self.author.username}'

class Comment(models.Model):
    comment_pic = models.ImageField(upload_to='images')
    comment_text = models.CharField(max_length=255)
    comment_author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comment_author')
    shot = models.ForeignKey(Shot, on_delete=models.CASCADE, null=True)   
    likers_comment = models.ManyToManyField(User, related_name='likers_comment')
    mention_comment = models.ManyToManyField(User, through='Comment_mention', related_name='mention_comment')

class Hashtag(models.Model):
    hashtag_text = models.CharField(max_length=100)
    shots = models.ManyToManyField(Shot)
    

class UserProfile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    user_pfp = models.ImageField(upload_to='images/users', blank=True)
    bio = models.CharField(max_length=255, blank=True)
    followers = models.ManyToManyField(User, related_name='followers', blank=True)

    def __str__(self) -> str:
        return f'{self.user.username} - {self.user.id} (UserProfile id: {self.id})' 

class Mention(models.Model):
    # 1-m many to a post, 1-m with a comment, 1-m with a user
    shot = models.ForeignKey(Shot, on_delete=models.CASCADE)
    who = models.ForeignKey(User, on_delete=models.CASCADE) # person @-ted
    is_shown = models.BooleanField(default=False)
    time_pub = models.DateTimeField(auto_now_add=True)

class Comment_mention(models.Model):
    # 1-m many to a post, 1-m with a comment, 1-m with a user
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    who = models.ForeignKey(User, on_delete=models.CASCADE) # person @-ted
    is_shown = models.BooleanField(default=False)
    time_pub = models.DateTimeField(auto_now_add=True)

# class Notfication(models.Model):
#     #type: atted, followed,
#     who = models.ForeignKey(User, on_delete=models.CASCADE) # person @-ted
#     shot = models.ForeignKey(Shot, on_delete=models.CASCADE, blank=True) 
#     time_pub = models.DateTimeField(auto_now_add=True)

mysite/headshot/views.py
from django.db import IntegrityError
from django.shortcuts import render, reverse, redirect
from .models import Shot, Hashtag, Mention, UserProfile, Comment
from django.contrib.auth.models import User
from django.db.models import Count
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages

def index(request):
    shots = Shot.objects.order_by("-time_pub")
    context = {'shots': shots}
    return render(request, 'headshot/home_page.html', context)

def popular(request):
    shots = Shot.objects.annotate(numoflikers=Count('likers')).order_by('-numoflikers')[:5]
    context = {'shots':shots}
    return render(request, 'headshot/popular.html', context)

def profile_page(request):
    userprofile = UserProfile.objects.get(user=request.user)
    return render(request, 'headshot/profile_page.html', {'userprofile':userprofile})

def test(request):
    shots = Shot.objects.order_by("-time_pub")
    context = {'shots': shots}
    return render(request, 'headshot/test.html', context)

def loginsignup(request):
    return render(request, 'headshot/loginsignup.html')

def post(request):
    return render(request, 'headshot/post.html')

def signup(request):
    username = request.POST['username']
    password = request.POST['password']
    user_pfp = request.FILES['user_pfp']
    try:
        user = User.objects.create_user(username=username, password=password)
    except IntegrityError: 
        messages.add_message(request, messages.ERROR, "This username has already been taken")
        return HttpResponseRedirect(reverse('shot:loginsignup')) 
    if user is not None:
        userp = UserProfile(user=user, user_pfp=user_pfp)
        userp.save()
        login(request, user)
        return redirect("shot:index")
    else: 
        return HttpResponseRedirect(reverse('shot:loginsignup')) 


def logon(request):
    try:
        username = request.POST['username'] 
        password = request.POST['password']

    except:
        return HttpResponseRedirect(reverse('shot:loginsignup')) 
    user = authenticate(username=username, password=password)
    if user is not None:
        login(request, user)
        return redirect("shot:index")
    else:
        return HttpResponseRedirect(reverse('shot:loginsignup')) 

def log_out(request):
    logout(request)
    return redirect('shot:loginsignup')

def like(request, shot_id):
    shot = Shot.objects.get(id=shot_id)
    shot.likers.add(request.user)
    return redirect(request.META['HTTP_REFERER'])

def unlike(request, shot_id):
    shot = Shot.objects.get(id=shot_id)
    shot.likers.remove(request.user)
    return redirect(request.META['HTTP_REFERER'])

def follow(request, author_id ):    
    celeb = UserProfile.objects.get(user=User.objects.get(id=author_id))
    celeb.followers.add(request.user)
    return redirect(request.META['HTTP_REFERER'])

def unfollow(request, author_id):
    celeb = UserProfile.objects.get(user=User.objects.get(id=author_id))
    celeb.followers.remove(request.user)
    return redirect(request.META['HTTP_REFERER'])

def post_comment(request, shot_id):
    if request.method == 'POST':
        comment_text = request.POST['comment_text']
        comment_pic = request.FILES['comment_pic']
        shot = Shot.objects.get(id=shot_id)
        comment = Comment(comment_pic=comment_pic, comment_text=comment_text, comment_author=request.user, shot=shot)
        comment.save()

        post_hashtag_mention(comment_text, shot)
        return redirect(request.META['HTTP_REFERER'])
         
    else:
        shot = Shot.objects.get(id=shot_id)
        context = {'shot':shot, 'comments':Comment.objects.filter(shot=shot)}
        return render(request, 'headshot/comment.html', context)

def author(request,author_id):
    user = User.objects.get(id=author_id)
    userprofile  = UserProfile.objects.get(user=user)
    context = {'author':user, 'authorprofile':userprofile, 'shots':Shot.objects.filter(author=user)}
    return render(request, 'headshot/user.html', context)


def hashtag(request, hashtag_text):
    try:
        hashtag = Hashtag.objects.get(hashtag_text=hashtag_text)
    except:
        return redirect('shot:index')
    context = {'hashtag_text': hashtag_text, 'shots':hashtag.shots.all()}
    print(context)
    return render(request, 'headshot/hashtag.html', context)

def mention(request, mention_text):
    try:
        who = User.objects.get(username=mention_text[1:])
        mentions = Mention.objects.filter(who=who)
        shots = []
        for mention in mentions:
            shots.append(mention.shot)
    except:
        return redirect('shot:index')
    context = {'mention_text': mention_text, 'shots':shots}
    return render(request, 'headshot/mention.html', context)

def post_hashtag_mention(text, shot):
    words = text.split()
    print(words)

    for word in words:
        if word and word[0] == "#":
            try:
                hashtag = Hashtag.objects.get(hashtag_text=word.strip().lower())
            except ObjectDoesNotExist:
                hashtag = Hashtag(hashtag_text=word.lower().strip())
                hashtag.save()
           
            hashtag.shots.add(shot)

        elif word and word[0] == "@":
            user = User.objects.get(username=word[1:])
            print(f'Posting. @{user.username}')

            mention = Mention(shot=shot, who=user)
            try:
                mention.save()
            except:
                pass

def post_shot(request):
    if request.method == 'POST':
        shot_text = request.POST['shot_text']
        shot_pic = request.FILES['shot_pic']
        shot = Shot(shot_pic=shot_pic, shot_text=shot_text, author=request.user)
        shot.save()

        post_hashtag_mention(shot_text, shot)
        return redirect(request.META['HTTP_REFERER'])
         
    else:
        return redirect(request.META['HTTP_REFERER'])

def delete(request, shot_id):
    shot = Shot.objects.get(id=shot_id)
    shot.delete()
    return redirect(request.META['HTTP_REFERER'])

def search(request):
    tag_text = request.GET.get('search', '').strip().lower()
    if tag_text[0] == '@':
        return HttpResponseRedirect(reverse('shot:mention', args=(tag_text, ))) 
    elif tag_text[0] == '#':
        return HttpResponseRedirect(reverse('shot:hashtag', args=(tag_text, )))
    else:
        tag_text = "#"+tag_text
        return HttpResponseRedirect(reverse('shot:hashtag', args=(tag_text, )))

def like_comment(request, comment_id):
    comment = Comment.objects.get(id=comment_id)
    comment.likers_comment.add(request.user)
    return redirect(request.META['HTTP_REFERER'])

def unlike_comment(request, comment_id):
    comment = Comment.objects.get(id=comment_id)
    comment.likers_comment.remove(request.user)
    return redirect(request.META['HTTP_REFERER'])

def delete_comment(request, comment_id):
    comment = Comment.objects.get(id=comment_id)
    comment.delete()
    return redirect(request.META['HTTP_REFERER'])

mysite/headshot/templates/headshot/comment.html
<!DOCTYPE html>

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <script src="https://kit.fontawesome.com/ecc259b3ee.js" crossorigin="anonymous"></script>

    <title>Comments</title>
</head>


<body>
    {% include 'headshot/navbar.html' %}
    <section class="section">
        <h1 class="title is-1 is-spaced">Comment page</h1>
    </section>
    <section class="section">    
        {% include 'headshot/display_shot.html' %}
    </section>

    <section class="section">
      <form method="post" enctype="multipart/form-data" action="{% url 'shot:post_comment' shot.id %}">
        {% csrf_token %}
        <p>
        <div class="file has-name">
            <label class="file-label">
                <input class="file-input" type="file" id="comment_pic" name="comment_pic" accept="image/*" required>
                <span class="file-cta">
                    <span class="file-icon">
                        <i class="fas fa-upload"></i>
                    </span>
                    <span class="file-label">
                        Post your comment shot
                    </span>
                </span>
            </label>
        </div>
        </p>
        <br>
        <p>
        <div class="field">
            <label class="label">Say something</label>
            <div class="control">
                <textarea class="textarea is-link"  placeholder="Add a description to go with your comment shot" name="comment_text"
                    id="comment_text"></textarea>
            </div>
        </div>
        </p>
        <div class="field is-grouped">
            <div class="control">
                <button class="button is-link" type="submit">Upload</button>
            </div>
        </div>
    </form>
</section>

    <section class="section">
      {% include 'headshot/display_comments.html' %}
    </section>

</body>

mysite/headshot/templates/headshot/display_comment.html
<div class="column">
    <article class="media">
        <div class="card">
            <div class="card-image" style="width: 300px;">
                <figure class="image is-300x300">
                    <img src="{{comment.comment_pic.url}}" alt="Placeholder image">
                </figure>
            </div>
            <div class="card-content">
                <div class="media">
                    <div class="media-content">
                        <p class="title is-4"><a href="{% url 'shot:author' comment.comment_author.id %}">{{comment.comment_author.username}}</a>
                        </p>
                        <p class="subtitle is-6">@{{comment.comment_author.username}}</p>
                    </div>
                </div>
    
                <div class="content">
                    {{shot.shot_text}}
                    <br>
                    <br>
                    <nav class="level is-mobile">
                        <div class="level-left">
                            {% if comment.comment_author.username == request.user.username %}
                            <a class="level-item" aria-label="bin" href="{% url 'shot:delete_comment' comment.id%}">
                                <span class="icon is-small">
                                    <i class="fa-solid fa-trash" aria-hidden="true"></i>
                                </span>
                            </a>&nbsp;        
                            {% endif %}
                            {% if request.user not in comment.likers_comment.all %}
                            <a class="level-item" aria-label="like" href="{% url 'shot:like_comment' comment.id %}">
                                {{comment.likers_comment.all|length}}&nbsp;
                                <span class="icon is-small">        
                                    <i class="fa-solid fa-thumbs-up" aria-label="like"></i>
                                </span>
                            </a>
                            {% else %}
                            <a class="level-item" aria-label="unlike" href="{% url 'shot:unlike_comment' comment.id %}">
                                {{comment.likers_comment.all|length}}&nbsp;
                                <span class="icon is-small">
                                    <i class="fa-solid fa-thumbs-down" aria-label="unlike"></i>
                                </span>
                            </a>
                            {% endif %}
                        </div>
                    </nav>
                </div>
                <br>
            </div>
        </div>
    </article>
</div>

mysite/headshot/templates/headshot/display_comments.html
{% for comment in comments %}
    {% include 'headshot/display_comment.html' %}
{% endfor %}

mysite/headshot/templates/headshot/display_shot.html
<div class="column">
    <article class="media">
        <div class="card">
            <div class="card-image" style="width: 300px;">
                <figure class="image is-300x300">
                    <img src="{{shot.shot_pic.url}}" alt="Placeholder image">
                </figure>
            </div>
            <div class="card-content">
                <div class="media">
                    <div class="media-left">
                        {% if shot.author.userprofile_set.all.0.user_pfp %}
                        <figure class="image is-48x48">
                            
                            <img src="{{shot.author.userprofile_set.all.0.user_pfp.url}}" alt="Placeholder image">
                        </figure>
                        {%endif %}
                    </div>
                    <div class="media-content">
                        <p class="title is-4"><a href="{% url 'shot:author' shot.author.id %}">{{shot.author.username}}</a>
                        </p>
                        <p class="subtitle is-6">@{{shot.author.username}}</p>
                    </div>
                </div>
    
                <div class="content">
                    {{shot.shot_text}}
                    <br>
                    <br>
                    <nav class="level is-mobile">
                        <div class="level-left">
                            {% if shot.author.username == request.user.username %}
                            <a class="level-item" aria-label="bin" href="{% url 'shot:delete' shot.id%}">
                                <span class="icon is-small">
                                    <i class="fa-solid fa-trash" aria-hidden="true"></i>
                                </span>
                            </a>&nbsp;        
                            {% endif %}
                            <a class="level-item" aria-label="reply" href="{% url 'shot:post_comment' shot.id %}">
                                <span class="icon is-small">
                                    <i class="fas fa-reply" aria-hidden="true"></i>
                                </span>
                            </a>&nbsp;
                            {% if request.user not in shot.likers.all %}
                            <a class="level-item" aria-label="like" href="/shot/like/{{shot.id}}">
                                {{shot.likers.all|length}}&nbsp;
                                <span class="icon is-small">        
                                    <i class="fa-solid fa-thumbs-up" aria-label="like"></i>
                                </span>
                            </a>
                            {% else %}
                            {{shot.likers.all|length}}&nbsp;
                            <a class="level-item" aria-label="like" href="/shot/unlike/{{shot.id}}">
                                <span class="icon is-small">
                                    <i class="fa-solid fa-thumbs-down" aria-label="unlike"></i>
                                </span>
                            </a>
                            {% endif %}
                        </div>
                    </nav>
                </div>
                <br>
            </div>
        </div>
    </article>
</div>

mysite/headshot/templates/headshot/display_shot2.html
<div class="tile is-vertical is-child">
    <article class="media">
        <div class="card">
            <div class="card-image" style="width: 300px;">
                <figure class="image is-300x300">
                    <img src="{{shot.shot_pic.url}}" alt="Placeholder image">
                </figure>
            </div>
            <div class="card-content">
                <div class="media">
                    <div class="media-left">
                        {% if shot.author.userprofile_set.all.0.user_pfp %}
                        <figure class="image is-48x48">
    
                            <img src="{{shot.author.userprofile_set.all.0.user_pfp.url}}" alt="Placeholder image">
                        </figure>
                        {%endif %}
                    </div>
                    <div class="media-content">
                        <p class="title is-4"><a href="{% url 'shot:author' shot.author.id %}">{{shot.author.username}}</a>
                        </p>
                        <p class="subtitle is-6">@{{shot.author.username}}</p>
                    </div>
                </div>
    
                <div class="content">
                    {{shot.shot_text}}
                    <br>
                    <br>
                    <nav class="level is-mobile">
                        <div class="level-left">
                            {% if shot.author.username == request.user.username %}
                            <a class="level-item" aria-label="bin" href="{% url 'shot:delete' shot.id%}">
                                <span class="icon is-small">
                                    <i class="fa-solid fa-trash" aria-hidden="true"></i>
                                </span>
                            </a>&nbsp;
                            {% endif %}
                            <a class="level-item" aria-label="reply" href="{% url 'shot:post_comment' shot.id %}">
                                <span class="icon is-small">
                                    <i class="fas fa-reply" aria-hidden="true"></i>
                                </span>
                            </a>&nbsp;
                            {% if request.user not in shot.likers.all %}
                            <a class="level-item" aria-label="like" href="/shot/like/{{shot.id}}">
                                {{shot.likers.all|length}}&nbsp;
                                <span class="icon is-small">
                                    <i class="fa-solid fa-thumbs-up" aria-label="like"></i>
                                </span>
                            </a>
                            {% else %}
                            {{shot.likers.all|length}}&nbsp;
                            <a class="level-item" aria-label="like" href="/shot/unlike/{{shot.id}}">
                                <span class="icon is-small">
                                    <i class="fa-solid fa-thumbs-down" aria-label="unlike"></i>
                                </span>
                            </a>
                            {% endif %}
                        </div>
                    </nav>
                </div>
                <br>
            </div>
        </div>
    </article>
</div>

mysite/headshot/templates/headshot/display_shots.html
<div class="columns is-multiline">
    {% for shot in shots %}
        {% include 'headshot/display_shot.html' %}
    {% endfor %}
</div>

mysite/headshot/templates/headshot/hashtag.html
<!DOCTYPE html>

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <script src="https://kit.fontawesome.com/ecc259b3ee.js" crossorigin="anonymous"></script>

    <title>{{hashtag_text}}</title>
</head>



<body>
    {% include 'headshot/navbar.html' %}
    <section class="section">
        <h1 class="title is-1 is-spaced">Posts with {{hashtag_text}}</h1>
    </section>
    <section class="section">
        {% include 'headshot/display_shots.html' %}
    </section>
    
</body>

</html>

mysite/headshot/templates/headshot/home_page.html
<!DOCTYPE html>

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <script src="https://kit.fontawesome.com/ecc259b3ee.js" crossorigin="anonymous"></script>

    <title>Shot</title>
</head>

<body>
    {% include 'headshot/navbar.html' %}
    <!--<tag class="has-background-danger"></tag>-->

    <section class="section">
        <h1 class="title is-1 is-spaced">Home</h1>
    </section>

    <section class="section">
        {% include 'headshot/display_shots.html' %}
    </section>

</body>

</html>

mysite/headshot/templates/headshot/mention.html
<!DOCTYPE html>

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <script src="https://kit.fontawesome.com/ecc259b3ee.js" crossorigin="anonymous"></script>

    <title>{{mention_text}}</title>
</head>


<body>
    <body>
        {% include 'headshot/navbar.html' %}
        <section class="section">
            <h1 class="title is-1 is-spaced">Mention page for {{mention_text}}</h1>
        </section>
        <section class="section">
            {% include 'headshot/display_shots.html' %}
        </section>
        
    </body>

</body>
</html>

mysite/headshot/templates/headshot/post.html
<!DOCTYPE html>

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <script src="https://kit.fontawesome.com/ecc259b3ee.js" crossorigin="anonymous"></script>

    <title>Post</title>
</head>


<body>
    {% include 'headshot/navbar.html' %}
    <section class="section">
        <h1 class="title is-1 is-spaced">Post your shot</h1>
    </section>

<section class="section">
    <form method="post" enctype="multipart/form-data" action="{% url 'shot:post_shot' %}">
      {% csrf_token %}
      <p>
      <div class="file has-name">
          <label class="file-label">
            <input class="file-input" type="file" id="shot_pic" name="shot_pic" accept="image/*" required>
              <span class="file-cta">
                  <span class="file-icon">
                      <i class="fas fa-upload"></i>
                  </span>
                  <span class="file-label">
                      Post your shot
                  </span>
              </span>
          </label>
      </div>
      </p>
      <br>
      <p>
      <div class="field">
          <label class="label">Say something</label>
          <div class="control">
            <textarea class="textarea is-link"  placeholder="Add a description to go with your shot" name="shot_text"
            id="shot_text"></textarea>
          </div>
      </div>
      </p>
      <div class="field is-grouped">
          <div class="control">
              <button class="button is-link" type="submit">Upload</button>
          </div>
      </div>
  </form>
</section>


</body>

mysite/headshot/templates/headshot/safe.html
<!DOCTYPE html>

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <script src="https://kit.fontawesome.com/ecc259b3ee.js" crossorigin="anonymous"></script>

    <title>Shot</title>
</head>

<body>
  
<section class="section">
        <h1 class="title is-1 is-spaced">Welcome {{request.user}}</h1>


        <form method="post" enctype="multipart/form-data" action="{% url 'shot:post_shot' %}">
            {% csrf_token %}
            <p>
            <div class="file has-name">
                <label class="file-label">
                    <input class="file-input" type="file" id="shot_pic" name="shot_pic" accept="image/*" required>
                    <span class="file-cta">
                        <span class="file-icon">
                            <i class="fas fa-upload"></i>
                        </span>
                        <span class="file-label">
                            Post your shot
                        </span>
                    </span>
                </label>
            </div>
            </p>
            <br>
            <p>
            <div class="field">
                <label class="label">Description</label>
                <div class="control">
                    <textarea class="textarea is-link"  placeholder="Add a description to go with your shot" name="shot_text"
                        id="shot_text"></textarea>
                </div>
            </div>
            </p>
            <div class="field is-grouped">
                <div class="control">
                    <button class="button is-link" type="submit">Upload</button>
                </div>
            </div>
        </form>
    </section>

    <section class="section">
        <form action="{% url 'shot:search' %}" method="get">
            <label for="shot">
                <h2>Search:</h2>
            </label>
            <p><input type="text" required placeholder="Search here" id="shot" name="search"></p>
            <input type="submit" value="Search">
        </form>
    </section>


    <section class="section">
        {% include 'headshot/display_shots.html' %}
    </section>

    <section class="section">
        <h2>Logout</h2>
        <form action="{% url 'shot:log_out' %}" method=post>
            {% csrf_token %}
            <p><input type="submit" value="Logout"></p>
        </form>
    </section>

</body>

</html>

mysite/headshot/templates/headshot/user.html
<!DOCTYPE html>

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <script src="https://kit.fontawesome.com/ecc259b3ee.js" crossorigin="anonymous"></script>

    <title>Shot</title>
</head>

<body>
    {% include 'headshot/navbar.html' %}
    <section class="section">
        <h1 class="title is-1 is-spaced">{{author.username}}'s posts: </h1>
    </section>


    <section class="section">
        {% include 'headshot/display_shots.html' %}
    </section>



    <!--<section class="section">
    {% if authorprofile %}
        {% if request.user not in authorprofile.followers.all %}
        <a href="{% url 'shot:follow' author.id %}">Follow</a>
        {% else %}
        <a href="{% url 'shot:unfollow' author.id %}">Unfollow</a>
        {% endif %}
    ({{authorprofile.followers.all|length}})
    {% endif %}
    </section>-->


</body>
</html>